Moonstone 2.0
ModdingX/Moonstone pull request #5
Opened 2022-07-11 19:10 UTC by noeppi-noeppi

Adds support for Modrinth and changes the `modlist.json` format to store more information. Also renames the package to `org.moddingx.moonstone`.

2022-07-12 20:01 UTC, noeppi-noeppi commented
When this is done, config detection from gradle won't be necessary any longer, so this fixes #3.

2022-07-19 15:35 UTC, noeppi-noeppi commented
Actually, it's Moonstone 1.0 as we have not released a 1.0 yet...

2022-07-19 17:04 UTC, MelanX requested changes
Only one thing, good luck with it!

2022-07-19 17:04 UTC, MelanX commented on src/main/scala/org/moddingx/moonstone/model/FileListIO.scala
> +    val in: Reader = new InputStreamReader(new URL("https://launchermeta.mojang.com/mc/game/version_manifest.json").openStream(), StandardCharsets.UTF_8)
Use `https://piston-meta.mojang.com/mc/game/version_manifest.json`, Mojang changed the location.

2022-07-20 18:57 UTC, merged